events {}

http {
    limit_req_zone $binary_remote_addr zone=req_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    server {
        listen 80;
        server_name ilia-petrov.xyz www.ilia-petrov.xyz;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name ilia-petrov.xyz www.ilia-petrov.xyz;

        ssl_certificate /etc/letsencrypt/live/ilia-petrov.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ilia-petrov.xyz/privkey.pem;

        limit_req zone=req_limit burst=20 nodelay;
        limit_conn conn_limit 20;

        location / {
            proxy_pass http://booking_app:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}